---
repos:
  - repo: git://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.1
    hooks:
      - id: remove-tabs

  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: detect-private-key
      - id: check-ast

  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        args: ['--line-length', '110']

  - repo: https://gitlab.com/PyCQA/flake8
    rev: '3.7.8'
    hooks:
      - id: flake8
        additional_dependencies: ['pep8-naming']
        # Ignore all format-related checks as Black takes care of those.
        args: ['--ignore', 'E123,E125', '--select', 'E,W,F,N', '--max-line-length=110']
